name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install runtime dependencies
        run: sudo apt-get update && sudo apt-get install --yes php-cli zip unzip
      - name: Test
        run: ./bin/test.sh
